apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avn128tnc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avn128tnc-nodejs 
  name: avn128tnc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: avn128tnc-nodejs 
